# Generated by Django 3.2.8 on 2021-10-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_ratelimit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateLimit',
            new_name='RateLimitUser',
        ),
    ]
